const home = require('./home');
const women = require('./women');
const men = require('./men');
const details = require('./details');
const saved = require('./savedFashion');
const unsaved = require('./unsavedItems');
const signup = require('./signup');
// const categories = require('./categories');
const router = require('express').Router();

router.get('/signup',signup.get);
router.post('/signup',signup.post);
router.get('/',home.disconutValue);
router.get('/details', details.get);
router.get('/details/:id', details.get);
// router.get('/categories',categories);
router.get('/women', women.get);
router.get('/men', men.discount);
router.get('/saved-fashion/:user_id', saved.get);
router.post('/saved', saved.post);
router.post('/unsaved', unsaved.post);
module.exports = router;
